# ========================================================================================
#
#                                   Leve Panel
#                                 Default Config
#
# ========================================================================================

# Panel Settings
[Panel]
pos = "bottom"  # "top", "bottom", "left", "right"
layer = "top"  # "background", "bottom", "top", "overlay"
size = 54 # pixels
roundness = 20
margin_top = 10
margin_bottom = 10
margin_left = 460
margin_right = 460
color = "#383B36" # Hex Color, or "rgba(40, 50, 160, 0.25)"
icon_size = 40
scroll_up = "swaymsg workspace prev"
scroll_down = "swaymsg workspace next"
#exclusive_zone = 52 # reserve space, defaults to size of panel


# Widgets appear left to right


# Center Widgets
[[Center]]
widget = "favorite"
icon = "folder-blue.png"
exec = "pcmanfm"
terminal = false

[[Center]]
widget = "favorite"
icon = "terminal.png"
exec = "foot"
terminal = false

[[Center]]
widget = "favorite"
icon = "google-chrome.png"
exec = "google-chrome"
terminal = false

[[Center]]
widget = "volume"
exec = "pavucontrol"
terminal = false

[[Center]]
widget = "power"
exec = "wlogout"
terminal = false

[[Center]]
widget = "menu"
exec = "griddle"
terminal = false


# Widgets on right side
# are added from right to left
